---
- name: Initialize VM
  hosts: proxmox_vm
  roles:
    - {role: basic_apt_package, basic_apt_package_apt_upgrade: true}
    - default_configs
    - install_docker
    - setup_exporter
    - install_tailscale
